#!/bin/sh

package=Game.app/Game.app
libs=$package/Contents/libs/
MacOS=$package/Contents/MacOS
mkdir -p $MacOS
mkdir -p $libs
cp ./Game $MacOS
cp -r ./Art $MacOS/Art
cp -r ./Music $MacOS/Music
mkdir -p $package/Contents/libs/
dylibbundler -od -b -ns -x $MacOS/Game -d $libs/
