#!/bin/sh

package=Game.app/Game.app
libs=$package/Contents/libs/
MacOS=$package/Contents/MacOS
Resources=$package/Contents/Resources
mkdir -p $MacOS
mkdir -p $libs
mkdir -p $Resources
cp ./Game $MacOS
cp -r ./Art $Resources/Art
cp -r ./Music $Resources/Music
mkdir -p $package/Contents/libs/
dylibbundler -od -b -ns -x $MacOS/Game -d $libs/
