#!/bin/sh

package=Game.app/Game.app
MacOS=$package/Contents/MacOS
mkdir -p $MacOS
cp ./Game $MacOS

mkdir -p $package/Contents/libs/
dylibbundler -od -b -ns -x $macos/game -d $package/Contents/libs/
